require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Seek' do
  config = use_native_modules!
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'react-native-image-crop-tools', :path => '../node_modules/react-native-image-crop-tools'
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  use_react_native!(:path => config["reactNativePath"])
  
  # target 'SeekTests' do
  #   inherit! :complete
    # Pods for testing
  # end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.74.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end