# available languages
# ar-SA, ca, cs, da, de-DE, el, en-AU, en-CA, en-GB, en-US, es-ES, 
# es-MX, fi, fr-CA, fr-FR, he, hi, hr, hu, id, it, ja, ko, ms, nl-NL, 
# no, pl, pt-BR, pt-PT, ro, ru, sk, sv, th, tr, uk, vi, zh-Hans, zh-Hant

languages(['en-US', 'ar-SA', 'ca', 'cs', 'da', 'de-DE',
  'es-ES', 'es-MX', 'fi', 'fr-FR', 'he', 'it', 'ja', 'nl-NL', 'no',
  'pt-BR', 'ro', 'ru', 'sv', 'tr', 'zh-Hant'
])

# monthly challenge
release_notes({
'en-US' => "December monthly challenge; bug fixes for species detail and observations screen in non-English languages",
'cs' => "K dispozici je nová výzva měsíce",
'da' => "December monthly challenge; bug fixes for species detail and observations screen in non-English languages",
'nl-NL' => "Elke maand is er een nieuwe uitdaging beschikbaar",
'fi' => "December monthly challenge; bug fixes for species detail and observations screen in non-English languages",
'fr-FR' => "Un nouveau défi mensuel est disponible",
'de-DE' => "Eine neue monatliche Mission ist verfügbar",
'zh-Hant' => "December monthly challenge; bug fixes for species detail and observations screen in non-English languages",
'it' => "Una nuova sfida mensile è disponibile",
'ja' => "December monthly challenge; bug fixes for species detail and observations screen in non-English languages",
'no' => "December monthly challenge; bug fixes for species detail and observations screen in non-English languages",
'pt-BR' => "December monthly challenge; bug fixes for species detail and observations screen in non-English languages",
'ro' => "Este disponibilă o nouă provocare lunară",
'he' => "קיים אתגר חודשי חדש",
'es-ES' => "Un nuevo desafío está disponible mensualmente",
'sv' => "December monthly challenge; bug fixes for species detail and observations screen in non-English languages",
'tr' => "December monthly challenge; bug fixes for species detail and observations screen in non-English languages",
'ca' => "Es proposa un nou repte mensual",
'ru' => "Доступно новое ежемесячное испытание",
'ar-SA' => "يوجد تحدٍّ شهري جديد متاح."
})


# release_notes({
# 'en-US' => "Bug fix",
# 'ar-SA' => "إصلاح الخلل",
# 'da' => "Fejlrettelse",
# 'nl-NL' => "bug fix",
# 'fi' => "bug fix",
# 'fr-FR' => "Correction d'un bug",
# 'de-DE' => "Bug-Fix",
# 'he' => "תיקון באגים",
# 'it' => "Risoluzione del problema",
# 'ja' => "バグ修正",
# 'no' => "Feilretting",
# 'pt-BR' => "correção de bug",
# 'ro' => "Rezolvarea unei erori",
# 'ru' => "Исправлена ​​ошибка",
# 'es-ES' => "Arreglo del fallo",
# 'sv' => "Buggfix",
# 'tr' => "Hata düzeltme",
# 'cs' => "Oprava chyby",
# 'ca' => "correcció d'errors",
# 'zh-Hant' => "Bug修復"
# })