# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

fastlane_require "dotenv"

before_all do
  Dotenv.overload ".env"
end

default_platform(:android)

platform :ios do
  desc "Distributes a beta version of Seek on TestFlight"
  lane :beta do
    get_certificates(username: ENV["USERNAME"]) # invokes cert
    get_provisioning_profile(username: ENV["USERNAME"],
                          app_identifier: ENV["APPLE_ID"]) # invokes sigh
    build_app(scheme: "Seek",
            workspace: "ios/Seek.xcworkspace",
            include_bitcode: true)
    upload_to_testflight(username: ENV["USERNAME"])
  end
end

platform :android do
 desc "Distributes an Android bundle to the Play Store beta track"
 lane :beta do
   gradle(task: "bundle", build_type: "Release", project_dir: "android" )
   upload_to_play_store(track: "beta", package_name: ENV["PACKAGE_NAME"])
 end

 desc "Build debug and test APK for screenshots"
  lane :build_for_screengrab do
    build_android_app(
      task: "assemble",
      build_type: "Debug"
    )
    build_android_app(
      task: "assemble",
      build_type: "AndroidTest"
    )
  end
end